# Generated by Django 2.2.4 on 2020-04-15 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('published_date', models.DateTimeField(default=datetime.datetime(2020, 4, 15, 12, 42, 59, 324033, tzinfo=utc))),
                ('content', models.TextField()),
                ('url_to_image', models.TextField()),
                ('news_url', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=500)),
            ],
        ),
    ]
