# Generated by Django 2.2.4 on 2020-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200415_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url_to_image',
        ),
    ]
